POST http://localhost:3000/pun
content-type: application/json

{
    "question": "test",
    "answer": "test"
}

###

POST http://localhost:3000/pun
content-type: application/json

{
    "question": "test",
    "answer": ""
}

###

POST http://localhost:3000/pun
content-type: application/json

{
    "question": "",
    "answer": "test"
}

###

POST http://localhost:3000/pun
content-type: application/json

{
    "question": "",
    "answer": ""
}

###

POST http://localhost:3000/pun
content-type: application/json

{
    "question": "test"
}

###

POST http://localhost:3000/pun
content-type: application/json

{
    "question": ""
}

###

POST http://localhost:3000/pun
content-type: application/json

{
    "answer": "test"
}

###

POST http://localhost:3000/pun
content-type: application/json

{
    "answer": ""
}

###

POST http://localhost:3000/pun
content-type: application/json

{}

###

POST http://localhost:3000/pun
content-type: application/json

###

GET http://localhost:3186/random-pun
content-type: application/json
